MVCStok/Models/Entities/CurrentAccount.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MVCStok.Models.Entities
{
    public class CurrentAccount
    {
        [Key]
        public int CurrentAccountID { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(30, ErrorMessage = "En fazla 30 karakter girebilirsiniz!")]
        [Required(ErrorMessage = "Bu alanı boş geçemezsiniz!")]
        public string CurrentAccountName { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(30, ErrorMessage = "En fazla 30 karakter girebilirsiniz!")]
        [Required(ErrorMessage = "Bu alanı boş geçemezsiniz!")]

        public string CurrentAccountLastname { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(30, ErrorMessage = "En fazla 30 karakter girebilirsiniz!")]
        [Required(ErrorMessage = "Bu alanı boş geçemezsiniz!")]
        public string CurrentAccountCity { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(50, ErrorMessage = "En fazla 50 karakter girebilirsiniz!")]
        [Required(ErrorMessage = "Bu alanı boş geçemezsiniz!")]
        public string CurrentAccountMail { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(50, ErrorMessage = "En fazla 50 karakter girebilirsiniz!")]
        public string CurrentAccountPassword { get; set; }

        public bool Durum { get; set; }

        public ICollection<SaleAct> SaleActList { get; set; }
    }
}

MVCStok/Controllers/CurrentAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCStok.Models.Entities;

namespace MVCStok.Controllers
{
    public class CurrentAccountController : Controller
    {
        // GET: CurrentAccount

        Context c = new Context();
        public ActionResult Index()
        {
            var values = c.CurrentAccountList.Where(x=>x.Durum==true).ToList();
            return View(values);
        }

        [HttpGet]
        public ActionResult NewCurrentAccount()
        {
            return View();
        }

        [HttpPost]
        public ActionResult NewCurrentAccount(CurrentAccount p)
        {
            if (!ModelState.IsValid)
            {
                return View("getCurrentAccount");
            }
            p.Durum = true;
            c.CurrentAccountList.Add(p);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        
        public ActionResult DeleteCurrentAccount(int id)
        {
            var cr = c.CurrentAccountList.Find(id);
            cr.Durum = false;
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult getCurrentAccount(int id)
        {
            var ca = c.CurrentAccountList.Find(id);
            return View("getCurrentAccount", ca);
        }

        public ActionResult UpdateCurrentAccount(CurrentAccount p)
        {
            if (!ModelState.IsValid)
            {
                return View("getCurrentAccount");
            }
            var ca = c.CurrentAccountList.Find(p.CurrentAccountID);
            ca.CurrentAccountName = p.CurrentAccountName;
            ca.CurrentAccountLastname = p.CurrentAccountLastname;
            ca.CurrentAccountCity = p.CurrentAccountCity;
            ca.CurrentAccountMail = p.CurrentAccountMail;
            c.SaveChanges();
            return RedirectToAction("Index");
        }


        public ActionResult CustomerSales(int id)
        {

            var cs = c.SaleActList.Where(x => x.CurrentAccountID == id).ToList();
            var cr = c.CurrentAccountList.Where(x => x.CurrentAccountID == id).Select(y => y.CurrentAccountName + " " + y.CurrentAccountLastname).FirstOrDefault();
            ViewBag.CurrentAccount = cr;
            return View(cs);
        }


    }
}

MVCStok/Views/CurrentAccount/CustomerSales.cshtml
@using MVCStok.Models.Entities
@model List<SaleAct>

@{
    ViewBag.Title = "CustomerSales";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<style>
    html,
    body {
        height: 100%;
    }

    body {
        margin: 0;
        background: linear-gradient(45deg, #49a09d, #5f2c82);
        font-family: sans-serif;
        font-weight: 100;
    }

    .container {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
    }


    table {
        width: 100%;
        margin-left: auto;
        margin-right: auto;
        9 border-collapse: collapse;
        overflow: hidden;
        box-shadow: 0 0 20px rgba(0,0,0,0.1);
    }

    th,
    td {
        padding: 15px;
        background-color: rgba(255,255,255,0.2);
        color: #fff;
    }

    th {
        text-align: left;
    }

    thead {
        th

    {
        background-color: #55608f;
    }

    }

    tbody {
        tr

    {
        &:hover

    {
        background-color: rgba(255,255,255,0.3);
    }

    }

    td {
        position: relative;
        &:hover

    {
        &:before

    {
        content: "";
        position: absolute;
        left: 0;
        right: 0;
        top: -9999px;
        bottom: -9999px;
        background-color: rgba(255,255,255,0.2);
        z-index: -1;
    }

    }
    }
    }
</style>

<table class="styled-table">
    <tr>
        <th>Satış ID</th>
        <th>Ürün</th>
        <th>Personel</th>
        <th>Ürün Fiyatı</th>
        <th>Adet</th>
        <th>Toplam Fiyat</th>
        <th>Tarih</th>
        <th>Yazdır</th>
    </tr>

    @foreach (var x in Model)
    {
        <tr>
            <td>@x.SalesID</td>
            <td>@x.ProductsList.ProductName</td>
            <td>@x.PersonalList.PersonalName @x.PersonalList.PersonalLastname</td>
            <td>@x.Product_Price</td>
            <td>@x.Quantity</td>
            <td>@x.Amount_Price</td>
            <td>@x.Date</td>
            <td><a href="#" class="btn btn-default" style="background-color:dodgerblue">Yazdır</a></td>
        </tr>
    }

</table>

MVCStok/Views/CurrentAccount/Index.cshtml
@using MVCStok.Models.Entities;
@model List<CurrentAccount>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<style>
    html,
    body {
        height: 100%;
    }

    body {
        margin: 0;
        background: linear-gradient(45deg, #49a09d, #5f2c82);
        font-family: sans-serif;
        font-weight: 100;
    }

    .container {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
    }


    table {
        width: 100%;
        margin-left: auto;
        margin-right: auto;9
        border-collapse: collapse;
        overflow: hidden;
        box-shadow: 0 0 20px rgba(0,0,0,0.1);
    }

    th,
    td {
        padding: 15px;
        background-color: rgba(255,255,255,0.2);
        color: #fff;
    }

    th {
        text-align: left;
    }

    thead {
        th

    {
        background-color: #55608f;
    }

    }

    tbody {
        tr

    {
        &:hover

    {
        background-color: rgba(255,255,255,0.3);
    }

    }

    td {
        position: relative;
        &:hover

    {
        &:before

    {
        content: "";
        position: absolute;
        left: 0;
        right: 0;
        top: -9999px;
        bottom: -9999px;
        background-color: rgba(255,255,255,0.2);
        z-index: -1;
    }

    }
    }
    }
</style>

<table class="styled-table">
    <tr>
        <th>Cari ID</th>
        <th>İsim</th>
        <th>Soyisim</th>
        <th>Şehir</th>
        <th>Email</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Detaylar</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.CurrentAccountID</td>
            <td>@x.CurrentAccountName</td>
            <td>@x.CurrentAccountLastname</td>
            <td>@x.CurrentAccountCity</td>
            <td>@x.CurrentAccountMail</td>
            <td><a href="/CurrentAccount/DeleteCurrentAccount/@x.CurrentAccountID" class="btn btn-danger">Sil</a></td>
            <td><a href="/CurrentAccount/getCurrentAccount/@x.CurrentAccountID" class="btn btn-warning">Güncelle</a></td>
            <td><a href="/CurrentAccount/CustomerSales/@x.CurrentAccountID" class="btn btn-default" style="background-color:greenyellow">Satış Geçmişi</a></td>
        </tr>
    }
</table>
<br />
<a href="/CurrentAccount/NewCurrentAccount" class="btn btn-info">Yeni Cari Ekle</a>

MVCStok/Views/CurrentAccount/NewCurrentAccount.cshtml
@model MVCStok.Models.Entities.CurrentAccount

@{
    ViewBag.Title = "NewCurrentAccount";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<form class="form-group" method="post">
    @Html.LabelFor(x => x.CurrentAccountName)
    @Html.TextBoxFor(x => x.CurrentAccountName, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CurrentAccountName, "", new { @style = "color:red" })
    <br />
    @Html.LabelFor(x => x.CurrentAccountLastname)
    @Html.TextBoxFor(x => x.CurrentAccountLastname, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CurrentAccountLastname, "", new { @style = "color:red" })
    <br />
    @Html.LabelFor(x => x.CurrentAccountCity)
    @Html.TextBoxFor(x => x.CurrentAccountCity, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CurrentAccountCity, "", new { @style = "color:red" })
    <br />
    @Html.LabelFor(x => x.CurrentAccountMail)
    @Html.TextBoxFor(x => x.CurrentAccountMail, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CurrentAccountMail, "", new { @style = "color:red" })
    <br />
    <button class="btn btn-info">Kaydet</button>
</form>

MVCStok/Views/CurrentAccount/getCurrentAccount.cshtml
@model MVCStok.Models.Entities.CurrentAccount

@{
    ViewBag.Title = "getCurrentAccount";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

@using(Html.BeginForm("UpdateCurrentAccount", "CurrentAccount", FormMethod.Post))
{
<div class="form-group">
    @Html.HiddenFor(x => x.CurrentAccountID)
    @Html.LabelFor(x => x.CurrentAccountName)
    @Html.TextBoxFor(x => x.CurrentAccountName, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CurrentAccountName, "", new { @style = "color:red" })
    <br />
    @Html.LabelFor(x => x.CurrentAccountLastname)
    @Html.TextBoxFor(x => x.CurrentAccountLastname, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CurrentAccountLastname, "", new { @style = "color:red" })
    <br />
    @Html.LabelFor(x => x.CurrentAccountCity)
    @Html.TextBoxFor(x => x.CurrentAccountCity, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CurrentAccountCity, "", new { @style = "color:red" })
    <br />
    @Html.LabelFor(x => x.CurrentAccountMail)
    @Html.TextBoxFor(x => x.CurrentAccountMail, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CurrentAccountMail, "", new { @style = "color:red" })
    <br />
    <button class="btn btn-warning">Güncelle</button>
</div>
}